### ISSUE TITLE
Crash log

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/octochemdb#50]
```
import_1   | 2022-05-01T05:39:07.678Z importOnePubmedFile Skipping pubmeds till: [object Object]
import_1   | /git/pubchem/node_modules/xml2json/lib/xml2json.js:173
import_1   |         throw new Error('There are errors in your xml file: ' + parser.getError());
import_1   |               ^
import_1   | Error: There are errors in your xml file: not well-formed (invalid token)
import_1   |     at module.exports (/git/pubchem/node_modules/xml2json/lib/xml2json.js:173:15)
import_1   |     at EventEmitter.<anonymous> (file:///git/pubchem/src/plugins/pubmeds/sync/utils/importOnePubmedFile.js:37:28)
import_1   |     at EventEmitter.emit (node:events:520:28)
import_1   |     at SAXStream.<anonymous> (/git/pubchem/node_modules/xml-flow/lib/xml-flow.js:142:15)
import_1   |     at SAXStream.emit (node:events:520:28)
import_1   |     at SAXParser.me._parser.<computed> [as onclosetag] (/git/pubchem/node_modules/sax/lib/sax.js:258:17)
import_1   |     at emit (/git/pubchem/node_modules/sax/lib/sax.js:624:35)
import_1   |     at emitNode (/git/pubchem/node_modules/sax/lib/sax.js:629:5)
import_1   |     at closeTag (/git/pubchem/node_modules/sax/lib/sax.js:889:7)
import_1   |     at SAXParser.write (/git/pubchem/node_modules/sax/lib/sax.js:1436:13)
import_1   |     at SAXStream.write (/git/pubchem/node_modules/sax/lib/sax.js:239:18)
import_1   |     at Gunzip.ondata (node:internal/streams/readable:754:22)
import_1   |     at Gunzip.emit (node:events:520:28)
import_1   |     at addChunk (node:internal/streams/readable:315:12)
import_1   |     at readableAddChunk (node:internal/streams/readable:289:9)
import_1   |     at Gunzip.Readable.push (node:internal/streams/readable:228:10)
import_1   |     at Zlib.processCallback (node:zlib:565:10)
import_1   | > node-pubchem@1.0.0 cron
import_1   | > DEBUG=* node -r dotenv/config src/sync/cron
import_1   | 2022-05-01T05:39:11.044Z cron sync: /git/pubchem/src/plugins//bioassays/sync/syncBioassays.js
import_1   | 2022-05-01T05:39:11.064Z SyncLast bioassays Get last bioassays file if new
import_1   | 2022-05-01T05:39:11.064Z SyncLast bioassays Syncing: https://ftp.ncbi.nlm.nih.gov/pubchem/Bioassay/Extras/bioactivities.tsv.gz to /originalData/bioassays/full
import_1   | 2022-05-01T05:39:11.540Z getFileIfNew New file size match local one (no need to fetch):2836484368/2836484368
import_1   | 2022-05-01T05:39:11.541Z SyncLast bioassays Get last bioassays file if new
import_1   | 2022-05-01T05:39:11.541Z SyncLast bioassays Syncing: https://ftp.ncbi.nlm.nih.gov/pubchem/Bioassay/Extras/bioassays.tsv.gz to /originalData/bioassays/full
import_1   | 2022-05-01T05:39:11.823Z getFileIfNew New file size match local one (no need to fetch):39819790/39819790
import_1   | 2022-05-01T05:39:11.824Z PubChemConnection Trying to connect to: mongodb://mongo:27017
import_1   | 2022-05-01T05:39:11.844Z PubChemConnection Got DB connection
import_1   | 2022-05-01T05:39:11.863Z syncBioassays file already processed
import_1   | 2022-05-01T05:39:11.865Z syncBioassays Deleting entries with wrong source: 0
import_1   | 2022-05-01T05:39:11.865Z cron Closing connection
import_1   | 2022-05-01T05:39:11.957Z cron sync: /git/pubchem/src/plugins//cmaups/sync/syncCmaups.js
import_1   | 2022-05-01T05:39:11.959Z SyncLast cmaups Get last cmaups file if new
import_1   | 2022-05-01T05:39:11.959Z SyncLast cmaups Syncing: http://bidd.group/CMAUP/downloadFiles/CMAUPv1.0_download_Ingredients_All.txt to /originalData/cmaups/full
import_1   | 2022-05-01T05:39:12.555Z getFileIfNew New file size match local one (no need to fetch):21506908/21506908
import_1   | 2022-05-01T05:39:12.556Z SyncLast cmaups Get last cmaups file if new
import_1   | 2022-05-01T05:39:12.556Z SyncLast cmaups Syncing: http://bidd.group/CMAUP/downloadFiles/CMAUPv1.0_download_Ingredient_Target_Associations_ActivityValues_References.txt to /originalData/cmaups/full
import_1   | 2022-05-01T05:39:13.133Z getFileIfNew New file size match local one (no need to fetch):1424665/1424665
import_1   | 2022-05-01T05:39:13.133Z SyncLast cmaups Get last cmaups file if new
import_1   | 2022-05-01T05:39:13.133Z SyncLast cmaups Syncing: http://bidd.group/CMAUP/downloadFiles/CMAUPv1.0_download_Plant_Ingredient_Associations_onlyActiveIngredients.txt to /originalData/cmaups/full
import_1   | 2022-05-01T05:39:13.705Z getFileIfNew New file size match local one (no need to fetch):1763024/1763024
import_1   | 2022-05-01T05:39:13.705Z SyncLast cmaups Get last cmaups file if new
import_1   | 2022-05-01T05:39:13.705Z SyncLast cmaups Syncing: http://bidd.group/CMAUP/downloadFiles/CMAUPv1.0_download_Plants.txt to /originalData/cmaups/full
import_1   | 2022-05-01T05:39:14.314Z getFileIfNew New file size match local one (no need to fetch):458276/458276
import_1   | 2022-05-01T05:39:14.314Z PubChemConnection Trying to connect to: mongodb://mongo:27017
import_1   | 2022-05-01T05:39:14.321Z PubChemConnection Got DB connection
import_1   | 2022-05-01T05:39:15.262Z syncCmaups file already processed
import_1   | 2022-05-01T05:39:15.263Z syncCmaups Deleting entries with wrong source: 0
import_1   | 2022-05-01T05:39:15.263Z cron Closing connection
import_1   | 2022-05-01T05:39:15.272Z cron sync: /git/pubchem/src/plugins//coconuts/sync/syncCoconuts.js
import_1   | 2022-05-01T05:39:15.274Z SyncLast coconuts Get last coconuts file if new
import_1   | 2022-05-01T05:39:15.274Z SyncLast coconuts Syncing: https://coconut.naturalproducts.net/download/mongo to /originalData/coconuts/full
import_1   | 2022-05-01T05:39:15.353Z getFileIfNew New file size match local one (no need to fetch):4923990393/4923990393
import_1   | 2022-05-01T05:39:15.353Z PubChemConnection Trying to connect to: mongodb://mongo:27017
import_1   | 2022-05-01T05:39:15.359Z PubChemConnection Got DB connection
import_1   | 2022-05-01T05:39:15.374Z syncCoconuts file already processed
import_1   | 2022-05-01T05:39:15.375Z syncCoconuts Deleting entries with wrong source: 0
import_1   | 2022-05-01T05:39:15.375Z cron Closing connection
import_1   | 2022-05-01T05:39:15.380Z cron sync: /git/pubchem/src/plugins//lotuses/sync/syncLotuses.js
import_1   | 2022-05-01T05:39:15.381Z SyncLast lotuses Get last lotuses file if new
import_1   | 2022-05-01T05:39:15.381Z SyncLast lotuses Syncing: https://lotus.naturalproducts.net/download/mongo to /originalData/lotuses/full
import_1   | 2022-05-01T05:39:15.459Z getFileIfNew New file size match local one (no need to fetch):766883885/766883885
import_1   | 2022-05-01T05:39:15.459Z PubChemConnection Trying to connect to: mongodb://mongo:27017
import_1   | 2022-05-01T05:39:15.464Z PubChemConnection Got DB connection
import_1   | 2022-05-01T05:39:15.476Z syncLotuses file already processed
import_1   | 2022-05-01T05:39:15.478Z syncLotuses Deleting entries with wrong source: 0
import_1   | 2022-05-01T05:39:15.478Z cron Closing connection
import_1   | 2022-05-01T05:39:15.496Z cron sync: /git/pubchem/src/plugins//npasses/sync/syncNpasses.js
import_1   | 2022-05-01T05:39:15.498Z SyncLast npasses Get last npasses file if new
import_1   | 2022-05-01T05:39:15.498Z SyncLast npasses Syncing: http://bidd.group/NPASS/downloadFiles/NPASSv1.0_download_naturalProducts_generalInfo.txt to /originalData/npasses/full
import_1   | 2022-05-01T05:39:16.070Z getFileIfNew New file size match local one (no need to fetch):4632141/4632141
import_1   | 2022-05-01T05:39:16.070Z SyncLast npasses Get last npasses file if new
import_1   | 2022-05-01T05:39:16.070Z SyncLast npasses Syncing: http://bidd.group/NPASS/downloadFiles/NPASSv1.0_download_naturalProducts_activities.txt to /originalData/npasses/full
import_1   | 2022-05-01T05:39:16.666Z getFileIfNew New file size match local one (no need to fetch):40841197/40841197
import_1   | 2022-05-01T05:39:16.666Z SyncLast npasses Get last npasses file if new
import_1   | 2022-05-01T05:39:16.666Z SyncLast npasses Syncing: http://bidd.group/NPASS/downloadFiles/NPASSv1.0_download_naturalProducts_properties.txt to /originalData/npasses/full
import_1   | 2022-05-01T05:39:17.272Z getFileIfNew New file size match local one (no need to fetch):10864336/10864336
import_1   | 2022-05-01T05:39:17.272Z SyncLast npasses Get last npasses file if new
import_1   | 2022-05-01T05:39:17.272Z SyncLast npasses Syncing: http://bidd.group/NPASS/downloadFiles/NPASSv1.0_download_naturalProducts_species_pair.txt to /originalData/npasses/full
import_1   | 2022-05-01T05:39:17.865Z getFileIfNew New file size match local one (no need to fetch):17730221/17730221
import_1   | 2022-05-01T05:39:17.865Z SyncLast npasses Get last npasses file if new
import_1   | 2022-05-01T05:39:17.865Z SyncLast npasses Syncing: http://bidd.group/NPASS/downloadFiles/NPASSv1.0_download_naturalProducts_speciesInfo.txt to /originalData/npasses/full
import_1   | 2022-05-01T05:39:18.437Z getFileIfNew New file size match local one (no need to fetch):3258675/3258675
import_1   | 2022-05-01T05:39:18.437Z PubChemConnection Trying to connect to: mongodb://mongo:27017
import_1   | 2022-05-01T05:39:18.442Z PubChemConnection Got DB connection
import_1   | 2022-05-01T05:39:24.393Z syncNpasses file already processed
import_1   | 2022-05-01T05:39:24.408Z syncNpasses Deleting entries with wrong source: 0
import_1   | 2022-05-01T05:39:24.408Z cron Closing connection
import_1   | 2022-05-01T05:39:24.463Z cron sync: /git/pubchem/src/plugins//pubmeds/sync/syncPubmed.js
import_1   | 2022-05-01T05:39:24.465Z PubChemConnection Trying to connect to: mongodb://mongo:27017
import_1   | 2022-05-01T05:39:24.473Z PubChemConnection Got DB connection
import_1   | 2022-05-01T05:39:24.478Z firstPubmedImport First importation has been completed. Should only update.
import_1   | 2022-05-01T05:39:24.479Z incrementalPubmedImport Synchronize incremental pubmed folder
import_1   | 2022-05-01T05:39:25.531Z syncFolder Skipped till: pubmed22n1300.xml.gz Size: 56312030/56312030
import_1   | 2022-05-01T05:39:25.538Z incrementalPubmedImport last file processed: /pubmeds/update/pubmed22n1170.xml.gz
import_1   | 2022-05-01T05:39:25.538Z incrementalPubmedImport starting with file /pubmeds/update/pubmed22n1170.xml.gz
import_1   | 2022-05-01T05:39:25.538Z incrementalPubmedImport Starting incremental update
import_1   | 2022-05-01T05:39:25.538Z incrementalPubmedImport Processing: pubmed22n1170.xml.gz
import_1   | 2022-05-01T05:39:25.540Z importOnePubmedFile Importing: pubmed22n1170.xml.gz
import_1   | 2022-05-01T05:39:25.585Z importOnePubmedFile Skipping pubmeds till: [object Object]
import_1   | /git/pubchem/node_modules/xml2json/lib/xml2json.js:173
import_1   |         throw new Error('There are errors in your xml file: ' + parser.getError());
import_1   |               ^
import_1   | Error: There are errors in your xml file: not well-formed (invalid token)
import_1   |     at module.exports (/git/pubchem/node_modules/xml2json/lib/xml2json.js:173:15)
import_1   |     at EventEmitter.<anonymous> (file:///git/pubchem/src/plugins/pubmeds/sync/utils/importOnePubmedFile.js:37:28)
import_1   |     at EventEmitter.emit (node:events:520:28)
import_1   |     at SAXStream.<anonymous> (/git/pubchem/node_modules/xml-flow/lib/xml-flow.js:142:15)
import_1   |     at SAXStream.emit (node:events:520:28)
import_1   |     at SAXParser.me._parser.<computed> [as onclosetag] (/git/pubchem/node_modules/sax/lib/sax.js:258:17)
import_1   |     at emit (/git/pubchem/node_modules/sax/lib/sax.js:624:35)
import_1   |     at emitNode (/git/pubchem/node_modules/sax/lib/sax.js:629:5)
import_1   |     at closeTag (/git/pubchem/node_modules/sax/lib/sax.js:889:7)
import_1   |     at SAXParser.write (/git/pubchem/node_modules/sax/lib/sax.js:1436:13)
import_1   |     at SAXStream.write (/git/pubchem/node_modules/sax/lib/sax.js:239:18)
import_1   |     at Gunzip.ondata (node:internal/streams/readable:754:22)
import_1   |     at Gunzip.emit (node:events:520:28)
import_1   |     at addChunk (node:internal/streams/readable:315:12)
import_1   |     at readableAddChunk (node:internal/streams/readable:289:9)
import_1   |     at Gunzip.Readable.push (node:internal/streams/readable:228:10)
import_1   |     at Zlib.processCallback (node:zlib:565:10)
import_1   | > node-pubchem@1.0.0 cron
import_1   | > DEBUG=* node -r dotenv/config src/sync/cron
import_1   | 2022-05-01T05:39:29.130Z cron sync: /git/pubchem/src/plugins//bioassays/sync/syncBioassays.js
import_1   | 2022-05-01T05:39:29.149Z SyncLast bioassays Get last bioassays file if new
import_1   | 2022-05-01T05:39:29.150Z SyncLast bioassays Syncing: https://ftp.ncbi.nlm.nih.gov/pubchem/Bioassay/Extras/bioactivities.tsv.gz to /originalData/bioassays/full
import_1   | 2022-05-01T05:39:29.613Z getFileIfNew New file size match local one (no need to fetch):2836484368/2836484368
import_1   | 2022-05-01T05:39:29.613Z SyncLast bioassays Get last bioassays file if new
import_1   | 2022-05-01T05:39:29.613Z SyncLast bioassays Syncing: https://ftp.ncbi.nlm.nih.gov/pubchem/Bioassay/Extras/bioassays.tsv.gz to /originalData/bioassays/full
import_1   | 2022-05-01T05:39:29.989Z getFileIfNew New file size match local one (no need to fetch):39819790/39819790
import_1   | 2022-05-01T05:39:29.990Z PubChemConnection Trying to connect to: mongodb://mongo:27017
import_1   | 2022-05-01T05:39:30.009Z PubChemConnection Got DB connection
import_1   | 2022-05-01T05:39:30.027Z syncBioassays file already processed
import_1   | 2022-05-01T05:39:30.029Z syncBioassays Deleting entries with wrong source: 0
import_1   | 2022-05-01T05:39:30.029Z cron Closing connection
import_1   | 2022-05-01T05:39:30.126Z cron sync: /git/pubchem/src/plugins//cmaups/sync/syncCmaups.js
import_1   | 2022-05-01T05:39:30.128Z SyncLast cmaups Get last cmaups file if new
import_1   | 2022-05-01T05:39:30.128Z SyncLast cmaups Syncing: http://bidd.group/CMAUP/downloadFiles/CMAUPv1.0_download_Ingredients_All.txt to /originalData/cmaups/full
import_1   | 2022-05-01T05:39:30.699Z getFileIfNew New file size match local one (no need to fetch):21506908/21506908
import_1   | 2022-05-01T05:39:30.699Z SyncLast cmaups Get last cmaups file if new
import_1   | 2022-05-01T05:39:30.699Z SyncLast cmaups Syncing: http://bidd.group/CMAUP/downloadFiles/CMAUPv1.0_download_Ingredient_Target_Associations_ActivityValues_References.txt to /originalData/cmaups/full
import_1   | 2022-05-01T05:39:31.273Z getFileIfNew New file size match local one (no need to fetch):1424665/1424665
import_1   | 2022-05-01T05:39:31.273Z SyncLast cmaups Get last cmaups file if new
import_1   | 2022-05-01T05:39:31.273Z SyncLast cmaups Syncing: http://bidd.group/CMAUP/downloadFiles/CMAUPv1.0_download_Plant_Ingredient_Associations_onlyActiveIngredients.txt to /originalData/cmaups/full
import_1   | 2022-05-01T05:39:31.851Z getFileIfNew New file size match local one (no need to fetch):1763024/1763024
import_1   | 2022-05-01T05:39:31.851Z SyncLast cmaups Get last cmaups file if new
import_1   | 2022-05-01T05:39:31.851Z SyncLast cmaups Syncing: http://bidd.group/CMAUP/downloadFiles/CMAUPv1.0_download_Plants.txt to /originalData/cmaups/full
import_1   | 2022-05-01T05:39:32.431Z getFileIfNew New file size match local one (no need to fetch):458276/458276
import_1   | 2022-05-01T05:39:32.431Z PubChemConnection Trying to connect to: mongodb://mongo:27017
import_1   | 2022-05-01T05:39:32.439Z PubChemConnection Got DB connection
import_1   | 2022-05-01T05:39:33.418Z syncCmaups file already processed
import_1   | 2022-05-01T05:39:33.420Z syncCmaups Deleting entries with wrong source: 0
import_1   | 2022-05-01T05:39:33.420Z cron Closing connection
import_1   | 2022-05-01T05:39:33.430Z cron sync: /git/pubchem/src/plugins//coconuts/sync/syncCoconuts.js
import_1   | 2022-05-01T05:39:33.431Z SyncLast coconuts Get last coconuts file if new
import_1   | 2022-05-01T05:39:33.431Z SyncLast coconuts Syncing: https://coconut.naturalproducts.net/download/mongo to /originalData/coconuts/full
import_1   | 2022-05-01T05:39:33.510Z getFileIfNew New file size match local one (no need to fetch):4923990393/4923990393
import_1   | 2022-05-01T05:39:33.510Z PubChemConnection Trying to connect to: mongodb://mongo:27017
import_1   | 2022-05-01T05:39:33.517Z PubChemConnection Got DB connection
import_1   | 2022-05-01T05:39:33.528Z syncCoconuts file already processed
import_1   | 2022-05-01T05:39:33.529Z syncCoconuts Deleting entries with wrong source: 0
import_1   | 2022-05-01T05:39:33.529Z cron Closing connection
import_1   | 2022-05-01T05:39:33.535Z cron sync: /git/pubchem/src/plugins//lotuses/sync/syncLotuses.js
import_1   | 2022-05-01T05:39:33.536Z SyncLast lotuses Get last lotuses file if new
import_1   | 2022-05-01T05:39:33.536Z SyncLast lotuses Syncing: https://lotus.naturalproducts.net/download/mongo to /originalData/lotuses/full
import_1   | 2022-05-01T05:39:33.614Z getFileIfNew New file size match local one (no need to fetch):766883885/766883885
import_1   | 2022-05-01T05:39:33.614Z PubChemConnection Trying to connect to: mongodb://mongo:27017
import_1   | 2022-05-01T05:39:33.619Z PubChemConnection Got DB connection
import_1   | 2022-05-01T05:39:33.630Z syncLotuses file already processed
import_1   | 2022-05-01T05:39:33.631Z syncLotuses Deleting entries with wrong source: 0
import_1   | 2022-05-01T05:39:33.631Z cron Closing connection
import_1   | 2022-05-01T05:39:33.637Z cron sync: /git/pubchem/src/plugins//npasses/sync/syncNpasses.js
import_1   | 2022-05-01T05:39:33.639Z SyncLast npasses Get last npasses file if new
import_1   | 2022-05-01T05:39:33.639Z SyncLast npasses Syncing: http://bidd.group/NPASS/downloadFiles/NPASSv1.0_download_naturalProducts_generalInfo.txt to /originalData/npasses/full
import_1   | 2022-05-01T05:39:34.210Z getFileIfNew New file size match local one (no need to fetch):4632141/4632141
import_1   | 2022-05-01T05:39:34.210Z SyncLast npasses Get last npasses file if new
import_1   | 2022-05-01T05:39:34.211Z SyncLast npasses Syncing: http://bidd.group/NPASS/downloadFiles/NPASSv1.0_download_naturalProducts_activities.txt to /originalData/npasses/full
import_1   | 2022-05-01T05:39:34.773Z getFileIfNew New file size match local one (no need to fetch):40841197/40841197
import_1   | 2022-05-01T05:39:34.773Z SyncLast npasses Get last npasses file if new
import_1   | 2022-05-01T05:39:34.773Z SyncLast npasses Syncing: http://bidd.group/NPASS/downloadFiles/NPASSv1.0_download_naturalProducts_properties.txt to /originalData/npasses/full
import_1   | 2022-05-01T05:39:35.340Z getFileIfNew New file size match local one (no need to fetch):10864336/10864336
import_1   | 2022-05-01T05:39:35.340Z SyncLast npasses Get last npasses file if new
import_1   | 2022-05-01T05:39:35.340Z SyncLast npasses Syncing: http://bidd.group/NPASS/downloadFiles/NPASSv1.0_download_naturalProducts_species_pair.txt to /originalData/npasses/full
import_1   | 2022-05-01T05:39:35.912Z getFileIfNew New file size match local one (no need to fetch):17730221/17730221
import_1   | 2022-05-01T05:39:35.912Z SyncLast npasses Get last npasses file if new
import_1   | 2022-05-01T05:39:35.912Z SyncLast npasses Syncing: http://bidd.group/NPASS/downloadFiles/NPASSv1.0_download_naturalProducts_speciesInfo.txt to /originalData/npasses/full
import_1   | 2022-05-01T05:39:36.499Z getFileIfNew New file size match local one (no need to fetch):3258675/3258675
import_1   | 2022-05-01T05:39:36.499Z PubChemConnection Trying to connect to: mongodb://mongo:27017
import_1   | 2022-05-01T05:39:36.504Z PubChemConnection Got DB connection
import_1   | 2022-05-01T05:39:42.203Z syncNpasses file already processed
import_1   | 2022-05-01T05:39:42.216Z syncNpasses Deleting entries with wrong source: 0
import_1   | 2022-05-01T05:39:42.216Z cron Closing connection
import_1   | 2022-05-01T05:39:42.259Z cron sync: /git/pubchem/src/plugins//pubmeds/sync/syncPubmed.js
import_1   | 2022-05-01T05:39:42.260Z PubChemConnection Trying to connect to: mongodb://mongo:27017
import_1   | 2022-05-01T05:39:42.263Z PubChemConnection Got DB connection
import_1   | 2022-05-01T05:39:42.268Z firstPubmedImport First importation has been completed. Should only update.
import_1   | 2022-05-01T05:39:42.268Z incrementalPubmedImport Synchronize incremental pubmed folder
import_1   | 2022-05-01T05:39:43.250Z syncFolder Skipped till: pubmed22n1300.xml.gz Size: 56312030/56312030
import_1   | 2022-05-01T05:39:43.259Z incrementalPubmedImport last file processed: /pubmeds/update/pubmed22n1170.xml.gz
import_1   | 2022-05-01T05:39:43.259Z incrementalPubmedImport starting with file /pubmeds/update/pubmed22n1170.xml.gz
import_1   | 2022-05-01T05:39:43.259Z incrementalPubmedImport Starting incremental update
import_1   | 2022-05-01T05:39:43.259Z incrementalPubmedImport Processing: pubmed22n1170.xml.gz
import_1   | 2022-05-01T05:39:43.261Z importOnePubmedFile Importing: pubmed22n1170.xml.gz
import_1   | 2022-05-01T05:39:43.308Z importOnePubmedFile Skipping pubmeds till: [object Object]
import_1   | /git/pubchem/node_modules/xml2json/lib/xml2json.js:173
import_1   |         throw new Error('There are errors in your xml file: ' + parser.getError());
import_1   |               ^
import_1   | Error: There are errors in your xml file: not well-formed (invalid token)
import_1   |     at module.exports (/git/pubchem/node_modules/xml2json/lib/xml2json.js:173:15)
import_1   |     at EventEmitter.<anonymous> (file:///git/pubchem/src/plugins/pubmeds/sync/utils/importOnePubmedFile.js:37:28)
import_1   |     at EventEmitter.emit (node:events:520:28)
import_1   |     at SAXStream.<anonymous> (/git/pubchem/node_modules/xml-flow/lib/xml-flow.js:142:15)
import_1   |     at SAXStream.emit (node:events:520:28)
import_1   |     at SAXParser.me._parser.<computed> [as onclosetag] (/git/pubchem/node_modules/sax/lib/sax.js:258:17)
import_1   |     at emit (/git/pubchem/node_modules/sax/lib/sax.js:624:35)
import_1   |     at emitNode (/git/pubchem/node_modules/sax/lib/sax.js:629:5)
import_1   |     at closeTag (/git/pubchem/node_modules/sax/lib/sax.js:889:7)
import_1   |     at SAXParser.write (/git/pubchem/node_modules/sax/lib/sax.js:1436:13)
import_1   |     at SAXStream.write (/git/pubchem/node_modules/sax/lib/sax.js:239:18)
import_1   |     at Gunzip.ondata (node:internal/streams/readable:754:22)
import_1   |     at Gunzip.emit (node:events:520:28)
import_1   |     at addChunk (node:internal/streams/readable:315:12)
import_1   |     at readableAddChunk (node:internal/streams/readable:289:9)
import_1   |     at Gunzip.Readable.push (node:internal/streams/readable:228:10)
import_1   |     at Zlib.processCallback (node:zlib:565:10)
import_1   | > node-pubchem@1.0.0 cron
import_1   | > DEBUG=* node -r dotenv/config src/sync/cron
import_1   | 2022-05-01T05:39:46.715Z cron sync: /git/pubchem/src/plugins//bioassays/sync/syncBioassays.js
import_1   | 2022-05-01T05:39:46.735Z SyncLast bioassays Get last bioassays file if new
import_1   | 2022-05-01T05:39:46.735Z SyncLast bioassays Syncing: https://ftp.ncbi.nlm.nih.gov/pubchem/Bioassay/Extras/bioactivities.tsv.gz to /originalData/bioassays/full
import_1   | 2022-05-01T05:39:47.110Z getFileIfNew New file size match local one (no need to fetch):2836484368/2836484368
import_1   | 2022-05-01T05:39:47.110Z SyncLast bioassays Get last bioassays file if new
import_1   | 2022-05-01T05:39:47.110Z SyncLast bioassays Syncing: https://ftp.ncbi.nlm.nih.gov/pubchem/Bioassay/Extras/bioassays.tsv.gz to /originalData/bioassays/full
import_1   | 2022-05-01T05:39:47.486Z getFileIfNew New file size match local one (no need to fetch):39819790/39819790
import_1   | 2022-05-01T05:39:47.487Z PubChemConnection Trying to connect to: mongodb://mongo:27017
import_1   | 2022-05-01T05:39:47.507Z PubChemConnection Got DB connection
import_1   | 2022-05-01T05:39:47.525Z syncBioassays file already processed
import_1   | 2022-05-01T05:39:47.527Z syncBioassays Deleting entries with wrong source: 0
import_1   | 2022-05-01T05:39:47.527Z cron Closing connection
import_1   | 2022-05-01T05:39:47.621Z cron sync: /git/pubchem/src/plugins//cmaups/sync/syncCmaups.js
import_1   | 2022-05-01T05:39:47.623Z SyncLast cmaups Get last cmaups file if new
import_1   | 2022-05-01T05:39:47.623Z SyncLast cmaups Syncing: http://bidd.group/CMAUP/downloadFiles/CMAUPv1.0_download_Ingredients_All.txt to /originalData/cmaups/full
import_1   | 2022-05-01T05:39:48.188Z getFileIfNew New file size match local one (no need to fetch):21506908/21506908
import_1   | 2022-05-01T05:39:48.189Z SyncLast cmaups Get last cmaups file if new
import_1   | 2022-05-01T05:39:48.189Z SyncLast cmaups Syncing: http://bidd.group/CMAUP/downloadFiles/CMAUPv1.0_download_Ingredient_Target_Associations_ActivityValues_References.txt to /originalData/cmaups/full
import_1   | 2022-05-01T05:39:48.764Z getFileIfNew New file size match local one (no need to fetch):1424665/1424665
import_1   | 2022-05-01T05:39:48.765Z SyncLast cmaups Get last cmaups file if new
import_1   | 2022-05-01T05:39:48.765Z SyncLast cmaups Syncing: http://bidd.group/CMAUP/downloadFiles/CMAUPv1.0_download_Plant_Ingredient_Associations_onlyActiveIngredients.txt to /originalData/cmaups/full
import_1   | 2022-05-01T05:39:49.336Z getFileIfNew New file size match local one (no need to fetch):1763024/1763024
import_1   | 2022-05-01T05:39:49.336Z SyncLast cmaups Get last cmaups file if new
import_1   | 2022-05-01T05:39:49.336Z SyncLast cmaups Syncing: http://bidd.group/CMAUP/downloadFiles/CMAUPv1.0_download_Plants.txt to /originalData/cmaups/full
import_1   | 2022-05-01T05:39:49.908Z getFileIfNew New file size match local one (no need to fetch):458276/458276
import_1   | 2022-05-01T05:39:49.908Z PubChemConnection Trying to connect to: mongodb://mongo:27017
import_1   | 2022-05-01T05:39:49.915Z PubChemConnection Got DB connection
import_1   | 2022-05-01T05:39:50.841Z syncCmaups file already processed
import_1   | 2022-05-01T05:39:50.842Z syncCmaups Deleting entries with wrong source: 0
import_1   | 2022-05-01T05:39:50.842Z cron Closing connection
import_1   | 2022-05-01T05:39:50.851Z cron sync: /git/pubchem/src/plugins//coconuts/sync/syncCoconuts.js
import_1   | 2022-05-01T05:39:50.853Z SyncLast coconuts Get last coconuts file if new
import_1   | 2022-05-01T05:39:50.853Z SyncLast coconuts Syncing: https://coconut.naturalproducts.net/download/mongo to /originalData/coconuts/full
import_1   | 2022-05-01T05:39:50.931Z getFileIfNew New file size match local one (no need to fetch):4923990393/4923990393
import_1   | 2022-05-01T05:39:50.931Z PubChemConnection Trying to connect to: mongodb://mongo:27017
import_1   | 2022-05-01T05:39:50.938Z PubChemConnection Got DB connection
import_1   | 2022-05-01T05:39:50.949Z syncCoconuts file already processed
import_1   | 2022-05-01T05:39:50.951Z syncCoconuts Deleting entries with wrong source: 0
import_1   | 2022-05-01T05:39:50.951Z cron Closing connection
import_1   | 2022-05-01T05:39:50.956Z cron sync: /git/pubchem/src/plugins//lotuses/sync/syncLotuses.js
import_1   | 2022-05-01T05:39:50.957Z SyncLast lotuses Get last lotuses file if new
import_1   | 2022-05-01T05:39:50.957Z SyncLast lotuses Syncing: https://lotus.naturalproducts.net/download/mongo to /originalData/lotuses/full
import_1   | 2022-05-01T05:39:51.035Z getFileIfNew New file size match local one (no need to fetch):766883885/766883885
import_1   | 2022-05-01T05:39:51.035Z PubChemConnection Trying to connect to: mongodb://mongo:27017
import_1   | 2022-05-01T05:39:51.040Z PubChemConnection Got DB connection
import_1   | 2022-05-01T05:39:51.053Z syncLotuses file already processed
import_1   | 2022-05-01T05:39:51.054Z syncLotuses Deleting entries with wrong source: 0
import_1   | 2022-05-01T05:39:51.054Z cron Closing connection
import_1   | 2022-05-01T05:39:51.071Z cron sync: /git/pubchem/src/plugins//npasses/sync/syncNpasses.js
import_1   | 2022-05-01T05:39:51.072Z SyncLast npasses Get last npasses file if new
import_1   | 2022-05-01T05:39:51.072Z SyncLast npasses Syncing: http://bidd.group/NPASS/downloadFiles/NPASSv1.0_download_naturalProducts_generalInfo.txt to /originalData/npasses/full
import_1   | 2022-05-01T05:39:51.647Z getFileIfNew New file size match local one (no need to fetch):4632141/4632141
import_1   | 2022-05-01T05:39:51.647Z SyncLast npasses Get last npasses file if new
import_1   | 2022-05-01T05:39:51.647Z SyncLast npasses Syncing: http://bidd.group/NPASS/downloadFiles/NPASSv1.0_download_naturalProducts_activities.txt to /originalData/npasses/full
import_1   | 2022-05-01T05:39:52.243Z getFileIfNew New file size match local one (no need to fetch):40841197/40841197
import_1   | 2022-05-01T05:39:52.243Z SyncLast npasses Get last npasses file if new
import_1   | 2022-05-01T05:39:52.243Z SyncLast npasses Syncing: http://bidd.group/NPASS/downloadFiles/NPASSv1.0_download_naturalProducts_properties.txt to /originalData/npasses/full
import_1   | 2022-05-01T05:39:52.817Z getFileIfNew New file size match local one (no need to fetch):10864336/10864336
import_1   | 2022-05-01T05:39:52.817Z SyncLast npasses Get last npasses file if new
import_1   | 2022-05-01T05:39:52.817Z SyncLast npasses Syncing: http://bidd.group/NPASS/downloadFiles/NPASSv1.0_download_naturalProducts_species_pair.txt to /originalData/npasses/full
import_1   | 2022-05-01T05:39:53.411Z getFileIfNew New file size match local one (no need to fetch):17730221/17730221
import_1   | 2022-05-01T05:39:53.411Z SyncLast npasses Get last npasses file if new
import_1   | 2022-05-01T05:39:53.411Z SyncLast npasses Syncing: http://bidd.group/NPASS/downloadFiles/NPASSv1.0_download_naturalProducts_speciesInfo.txt to /originalData/npasses/full
import_1   | 2022-05-01T05:39:53.982Z getFileIfNew New file size match local one (no need to fetch):3258675/3258675
import_1   | 2022-05-01T05:39:53.982Z PubChemConnection Trying to connect to: mongodb://mongo:27017
import_1   | 2022-05-01T05:39:53.987Z PubChemConnection Got DB connection
import_1   | 2022-05-01T05:39:59.149Z syncNpasses file already processed
import_1   | 2022-05-01T05:39:59.164Z syncNpasses Deleting entries with wrong source: 0
import_1   | 2022-05-01T05:39:59.164Z cron Closing connection
import_1   | 2022-05-01T05:39:59.204Z cron sync: /git/pubchem/src/plugins//pubmeds/sync/syncPubmed.js
import_1   | 2022-05-01T05:39:59.205Z PubChemConnection Trying to connect to: mongodb://mongo:27017
import_1   | 2022-05-01T05:39:59.208Z PubChemConnection Got DB connection
import_1   | 2022-05-01T05:39:59.211Z firstPubmedImport First importation has been completed. Should only update.
import_1   | 2022-05-01T05:39:59.211Z incrementalPubmedImport Synchronize incremental pubmed folder
```

**Comment by RicardoSilvestr** [comment]
already solved
